### ISSUE TITLE
TK #3 - Realizar modelo conceptual

### ISSUE THREAD

**Issue by veros7821** [classroomEntreRios/proyecto-g2d-proyecto-g2d#3]
Desarrollo de diagrama intermedio para armado de diagrama de clases

**Comment by Northman82** [comment]
proyecto-g2d-proyecto-g2d/Grupo2D_DER.jpg
[https://github.com/classroomEntreRios/proyecto-g2d-proyecto-g2d/blob/main/Grupo2D_DER.jpg](url)

**Comment by Northman82** [comment]
Subí link de el Modelo Conceptual.

**Comment by veros7821** [comment]
![Grupo2D_ModeloER(1)](https://user-images.githubusercontent.com/19860351/108378699-037df280-71e4-11eb-83ce-fdc0fbbfdf54.jpg)

**Comment by veros7821** [comment]
diagrama relacional actualizado
