### ISSUE TITLE
Realizar diagrama de clases

### ISSUE THREAD

**Issue by veros7821** [classroomEntreRios/proyecto-g2d-proyecto-g2d#4]
Realización de diagrama de clases

**Comment by TCristhian** [comment]
https://app.diagrams.net/#G11a42njm1bodphVdPvdAnHYkS3ARoiKTV

**Comment by TCristhian** [comment]
Acabo de subir el enlace del diagrama de clases realizado en diagrams.net

**Comment by veros7821** [comment]
https://app.diagrams.net/#G11a42njm1bodphVdPvdAnHYkS3ARoiKTV

Diagrama actualizado
