### ISSUE TITLE
TK # 7 - Creación de base de datos

### ISSUE THREAD

**Issue by veros7821** [classroomEntreRios/proyecto-g2d-proyecto-g2d#7]
Se crea la base de datos en SQL

**Comment by Guiwa3** [comment]
Subo base de datos #7
[SQLQuery.zip](https://github.com/classroomEntreRios/proyecto-g2d-proyecto-g2d/files/5962905/SQLQuery.zip)

**Comment by veros7821** [comment]
[SQLQuery_actualizacion.zip](https://github.com/classroomEntreRios/proyecto-g2d-proyecto-g2d/files/5999370/SQLQuery_actualizacion.zip)

Agregado de 2 tablas para fotos y modificación de ciudades.
